//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class Message
{
	public String message;
	public float duration;
	public MessageEffect effect;
	public float startedRenderingOn;

	public enum MessageEffect
	{
		OVERSPRITE
	}
	public Message (String message, float duration, MessageEffect effect)
	{
		this.message = message;
		this.duration = duration;
		this.effect = effect;
	}
}


